### ISSUE TITLE
Never use windows-style path separators in aurelia.json

### ISSUE THREAD

**Issue by jdanyow** [aurelia/cli#332] opened 2016-09-22 21:37 UTC
On Windows, `au new` will create an aurelia.json with windows-style path separators (eg `"src\\**\\*.js"`). Windows aurelia.json files do not work on other platforms.

Using the `/` character for a separator works on all platforms.

**Comment by mattbrooks2010** [comment] 2016-09-23 22:15
Worth noting that `aurelia-cli` v0.20.0 also uses `\` on Windows when generating revision numbers / file hashes for generated bundles.

Example diff:

![image](https://cloud.githubusercontent.com/assets/2045274/18802878/95e14136-81e3-11e6-8315-56887fc9857b.png)

**Comment by EisenbergEffect** [comment] 2016-09-23 22:24
We need to put a general purpose solution in place to handle this
consistently. There is at least one other place that has this bug as well.

**Comment by AStoker** [comment] 2016-10-04 17:33
When dealing with revisions and changing the `index.html` file, it uses Node's Path module to create a path. This means that if it's compiled on windows, it'll use the backslash, and on Unix, it'll use the forward slash. I'll have a PR addressing the changing of the path in the index file soon. But we should probably change the default configuration that's generated by `au new` as well.

**Comment by AStoker** [comment] 2016-10-06 18:08
@EisenbergEffect, seems to enforce the non windows backslash we'll need to replace any place that is using `path.join` since that's platform specific and if compiled on windows will generate the backslash. Should we roll our own path join tool (what I'm would be the way to go), or is there some other approach you'd like to take?

**Comment by EisenbergEffect** [comment] 2016-10-06 18:29
That was what I was thinking.

**Comment by AStoker** [comment] 2016-10-06 19:27
If somebody wants to beat me to it, you could add this function to some general util and use it everywhere `path.join` is used.
``` javascript
function joinPath(){
	var joinedPaths = path.join.apply(null, arguments);
	if(process.platform == 'win32'){
		joinedPaths = joinedPaths.replace(/\\/g, '/');
	}
	return joinedPaths;
}
```
I gotta finish up getting the config generator to load up external config generators before I can work on this.

**Comment by mattbrooks2010** [comment] 2016-10-07 09:51
Another instance of this issue appears in `vendor-bundle.js`

```js
function _aureliaConfigureModuleLoader() {
    requirejs.config({
        baseUrl: "src/",
        paths: {
            text: "../wwwroot/scripts/text",
            "aurelia-animator-css": "../node_modules\\aurelia-animator-css\\dist\\amd\\aurelia-animator-css",
            "aurelia-dependency-injection": "../node_modules\\aurelia-dependency-injection\\dist\\amd\\aurelia-dependency-injection",
            "aurelia-framework": "../node_modules\\aurelia-framework\\dist\\amd\\aurelia-framework",
            "aurelia-bootstrapper": "../node_modules\\aurelia-bootstrapper\\dist\\amd\\aurelia-bootstrapper",
            "aurelia-binding": "../node_modules\\aurelia-binding\\dist\\amd\\aurelia-binding",
            "aurelia-event-aggregator": "../node_modules\\aurelia-event-aggregator\\dist\\amd\\aurelia-event-aggregator",
            "aurelia-history": "../node_modules\\aurelia-history\\dist\\amd\\aurelia-history",
            "aurelia-history-browser": "../node_modules\\aurelia-history-browser\\dist\\amd\\aurelia-history-browser",
            "aurelia-loader": "../node_modules\\aurelia-loader\\dist\\amd\\aurelia-loader",
            "aurelia-http-client": "../node_modules\\aurelia-http-client\\dist\\amd\\aurelia-http-client",
            "aurelia-loader-default": "../node_modules\\aurelia-loader-default\\dist\\amd\\aurelia-loader-default",
            "aurelia-logging": "../node_modules\\aurelia-logging\\dist\\amd\\aurelia-logging",
            "aurelia-logging-console": "../node_modules\\aurelia-logging-console\\dist\\amd\\aurelia-logging-console",
            "aurelia-metadata": "../node_modules\\aurelia-metadata\\dist\\amd\\aurelia-metadata",
            "aurelia-pal": "../node_modules\\aurelia-pal\\dist\\amd\\aurelia-pal",
            "aurelia-pal-browser": "../node_modules\\aurelia-pal-browser\\dist\\amd\\aurelia-pal-browser",
            "aurelia-path": "../node_modules\\aurelia-path\\dist\\amd\\aurelia-path",
            "aurelia-route-recognizer": "../node_modules\\aurelia-route-recognizer\\dist\\amd\\aurelia-route-recognizer",
            "aurelia-polyfills": "../node_modules\\aurelia-polyfills\\dist\\amd\\aurelia-polyfills",
            "aurelia-router": "../node_modules\\aurelia-router\\dist\\amd\\aurelia-router",
            "aurelia-task-queue": "../node_modules\\aurelia-task-queue\\dist\\amd\\aurelia-task-queue",
            "aurelia-templating": "../node_modules\\aurelia-templating\\dist\\amd\\aurelia-templating",
            "aurelia-templating-binding": "../node_modules\\aurelia-templating-binding\\dist\\amd\\aurelia-templating-binding",
            moment: "../node_modules\\moment\\moment"
        },
        packages: [{
            name: "aurelia-templating-resources",
            location: "../node_modules/aurelia-templating-resources/dist/amd",
            main: "aurelia-templating-resources"
        }, {
            name: "aurelia-templating-router",
            location: "../node_modules/aurelia-templating-router/dist/amd",
            main: "aurelia-templating-router"
        }, {
            name: "aurelia-validation",
            location: "../node_modules/aurelia-validation/dist/amd",
            main: "aurelia-validation"
        }, {
            name: "nprogress",
            location: "../node_modules/nprogress",
            main: "nprogress"
        }],
        stubModules: ["text"],
        shim: {}
    })
}
```

Incidentally, are the `baseUrl`, `paths` and `packages` entries actually required, given all modules are bundled? The value for `baseUrl` is technically wrong, at least for an Aurelia CLI project scaffolded within an ASP.NET Core project directory.

**Comment by einmaliger** [comment] 2016-10-11 17:25
This really should be fixed. I'm probably not the only one who gets a bad first impression from Aurelia when an app breaks once it's cloned to a Linux system. The error I got is not very helpful ('script error').

May I suggest using [path.posix.join()](https://nodejs.org/api/path.html#path_path_posix) for creating the strings, e.g., `path.posix.join('foo', 'bar')` becomes `'foo/bar`

**Comment by MeirionHughes** [comment] 2016-10-11 17:30
is path.posix.join() the recommended approach for cross platform?

**Comment by simonmurdock** [comment] 2016-10-12 07:53
I also ran into this issue yesterday where i started development on windows and then after a bit of head scratching had to "re new" the project on the mac and merge the changes in.

**Comment by lunicleonid** [comment] 2016-10-23 17:38
Still present in 0.21.0 :( Generated the project on Windows 10 and my colleague that is using a Mac spent some time figuring out why the project in not working on his machine.

**Comment by golavr** [comment] 2016-10-23 22:30
It's also affects the ability to debug (visual studio code) with source maps
**_app-bundle.js.map_**
{"version":3,"sources":["src/app.js", ...
 
![image](https://cloud.githubusercontent.com/assets/22896741/19629904/77ea4798-9987-11e6-9665-5d349df68f4a.png)


After changing the **_aurelia.json_** from` \\` to `/`
**_app-bundle.js.map_**
{"version":3,"sources":["app.js", ...
 
![image](https://cloud.githubusercontent.com/assets/22896741/19629906/85ab7f00-9987-11e6-9b07-0f52093f14dd.png)

Debug is working…
I wasted a lot of time finding the root cause, hope it will help others

**Comment by AStoker** [comment] 2016-10-24 14:45
Anybody actively looking at this? If not, I have a bit of bandwidth I'm going to spend to get it fixed.

**Comment by EisenbergEffect** [comment] 2016-10-24 15:19
Please go for it :)

**Comment by AStoker** [comment] 2016-10-24 21:02
I went for minimal changes. I think we only needed to change the path separators for user facing code. I'd appreciate someone else taking a look and confirming that this works across devices for more than just me.
https://github.com/aurelia/cli/pull/394

**Closed** 2016-11-08 15:58 UTC
Labels: bug, help wanted
