### ISSUE TITLE
Error when using material-design-iconic-font with new CLI/require

### ISSUE THREAD

**Issue by cluka** [aurelia/cli#934] opened 2018-10-11 12:41 UTC
**I'm submitting a bug report**

* **Library Version:**
^1.0.0-beta.1

**Please tell us about your environment:**
* **Operating System:**
Windows [10]

* **Node Version:**
10.10.0

* **NPM Version:**
6.4.1

* **Browser:**
all

* **Language:**
TypeScript 3.0.1

* **Loader/bundler:**
RequireJS

**Current behavior:**
**au start** displays an error when it tries to bundle **material-design-iconic-font**

* **What is the expected behavior?**
The application should start without error

Reproduce:
1. npm install aurelia-cli -g
2. au new
3. ... selected custom bundler then selected RequireJS
4. restored packages with yarn
5. yarn add material-design-iconic-font
6. Add 
`"copyFiles":{
    "node_modules/material-design-iconic-font/dist/fonts/*":"material-design-iconic-font/dist/fonts"
  },` into aurelia.json after "bundles"
7. Add
`<require from="material-design-iconic-font/dist/css/material-design-iconic-font.min.css"></require>`
into app.html
8. au run

Error is in the image
![cli-error](https://user-images.githubusercontent.com/1827208/46804555-346fd200-cd63-11e8-95bb-9f888bdc91a3.png)

* **What is the motivation / use case for changing the behavior?**

**Comment by zewa666** [comment] 2018-10-11 16:04
@huochunpeng the main of the package is [an array](https://github.com/zavoloklom/material-design-iconic-font/blob/master/package.json#L13-L16). Never seen that

**Comment by cluka** [comment] 2018-10-11 17:16
Ok.
So it's all ok with my registration of the font in Aurelia bundler?
And this font does work without problem in Aurelia webpack

**Comment by zewa666** [comment] 2018-10-11 17:18
@cluka actually no idea, but thats what I'd guess. Just mentioned that I wasn't aware you could use an array for main, so perhaps this is causing the new aurelia auto-tracer to choke

**Comment by huochunpeng** [comment] 2018-10-11 20:40
There are two issues here.

1. strange main. They definitely didn't follow spec https://docs.npmjs.com/files/package.json#main
This is not a bug for us to fix, it's one for them.

This issue can be fixed with an explicit config
```
"dependencies": [
  //...
  {
    "name": "material-design-iconic-font",
    "path": "../node_modules/material-design-iconic-font",
    "main": "dist/css/material-design-iconic-font.min.css"
  }
]
```

For that reason, this issue can be closed.

2. I saw you updated your post to use `<require from="some.css"></require>`. cli+requirejs has never supported `import "some.css"` in js file, our cli+webpack supports it with `style-loader` plugin.

I think it could be a good improvement to cli+requirejs to support `import "some.css"`, so people can easily migrate their code from webpack app to requirejs app. I will keep it on my todo list.

**Comment by huochunpeng** [comment] 2018-10-12 00:05
I will make cli more resilient in this situation, instead of panic, I can ignore the malformed main. You will see a missing main warning, but css import will still works.

**Closed** 2018-10-12 00:37 UTC

**Comment by huochunpeng** [comment] 2018-10-12 07:50
Congratulations for migrating from webpack to cli bundler!

It will take some time to heal your trauma, you might still wake up in nightmare in next few weeks.
Deep breathe, brother, Deep breathe... it was all over now.
🤣

**Comment by cluka** [comment] 2018-10-12 09:15
Lol
