### ISSUE TITLE
Replaced the bundle js path of the index.html: / -> \ (see screenshot)

### ISSUE THREAD

**Issue by xiwc** [aurelia/cli#367] opened 2016-10-08 02:55 UTC
**I'm submitting a bug report**
- **Library Version:**
  "aurelia-framework": "^1.0.0",

**Please tell us about your environment:**
- **Operating System:**
  Windows [7]
- **Node Version:**
  v4.4.2
- **NPM Version:**
  3.10.5
- **JSPM OR Webpack AND Version**
  aurelia-cli version: 0.20.2
- **Browser:**
  Chrome 52.0.2743.116 m
- **Language:**
  ESNext

**Current behavior:**
### Replaced the bundle js path of the index.html: / -> \ (see screenshot)

![image](https://cloud.githubusercontent.com/assets/8816203/19209557/3e2047c8-8d3f-11e6-82cb-17e4b015cd4c.png)

**Comment by EisenbergEffect** [comment] 2016-10-08 03:01
@AStoker Is this a dupe of the path separator issue we're tracking?

**Comment by AStoker** [comment] 2016-10-10 14:17
@EisenbergEffect, it seems most of this conversation is being directed here (https://github.com/aurelia/cli/issues/332). While that issue specifically mentions the aurelia.json file, it would be worth (I think) modifying that issue name and tracking all these issues there.

**Comment by AStoker** [comment] 2016-10-10 14:17
This specific issue is mentioned here (https://github.com/aurelia/cli/issues/332#issuecomment-249315271)

**Comment by JeroenVinke** [comment] 2017-03-28 21:38
@AStoker can we close this one?

**Comment by AStoker** [comment] 2017-03-29 20:14
Pretty sure this has been resolved. If not, please reopen.

**Closed by AStoker** 2017-03-29 20:14 UTC
Labels: bug
