### ISSUE TITLE
au run --env dev --watch takes 10 minutes years to do Tracing...

### ISSUE THREAD

**Issue by Narven** [aurelia/cli#421] opened 2016-11-24 01:44 UTC
Hi

Why is that every time i run `au run --env dev --watch` it takes huge amount of time to do this tracing weirdinesss...

```
...
Tracing view-model/organizations/other/header...
Tracing view-model/profile/followers/followers...
Tracing view-model/profile/following/following...
Tracing view-model/profile/media/media...
Tracing view-model/profile/settings/basic-info...
Tracing view-model/profile/settings/email-preferences...
Tracing me
Tracing you
Tracing Trump
...
```

This crap looks like a anti-virus scanning my computer taking +10 minutes... Is this really necessary while in dev? Do I really have to go and eat something every time i run that command?
This is going to increase a lot for each js file that i code? in 5 months is going to take 30 minutes.

Is this normal?

thanks

**Comment by EisenbergEffect** [comment] 2016-11-24 02:03
This is a duplicate of another performance issue we have tracked. We also have a PR just in today that makes a huge improvement to the performance. That will be merged and is planned for release within the next week.

**Comment by Narven** [comment] 2016-11-24 02:04
thats awesome. thanks

**Closed by EisenbergEffect** 2016-11-24 02:03 UTC

**Comment by EisenbergEffect** [comment] 2016-11-24 02:07
Sorry for the inconvenience. The CLI still has some alpha qualities, performance being one of them. Hopefully the upcoming release will fix it for you. If it doesn't, please let me know. As an alternative, you might look into Webpack, if the issue persists after this release. In the future, we're going to merge Webpack support into the CLI.

**Comment by Narven** [comment] 2016-11-24 02:12
No worries. is just a bit annoying the delay, specially because of manually inserting data info aurelia.json (i never get that thing right the first time) so when i run the `au run...` it always breaks a few times.

I think it would be a huge improvement if the aurelia.json would not be a manual process.

**Comment by EisenbergEffect** [comment] 2016-11-24 02:21
We've got a community group building out a new CLI feature per my spec, to eliminate the manual editing of aurelia.json .  We are all looking forward to that :)

**Comment by Narven** [comment] 2016-11-24 02:23
Thats really awesome work. thanks :D
