### ISSUE TITLE
au run starts downloading a file in Opera

### ISSUE THREAD

**Issue by ed0wolf** [aurelia/cli#446] opened 2016-12-27 07:04 UTC
**I'm submitting a bug report**

* **Library Version:**
0.23.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.0.0

* **NPM Version:**
3.10.8

* **Browser:**
Opera 42

* **Language:**
TypeScript 2.1.4

**Current behavior:**
When running 'au run' and then browsing to localhost:9000 in Opera it starts downloading a file. In Chrome it works as expected.

**Expected/desired behavior:**
In Opera it should the same as Chrome, which is top open the page as a website.

**Comment by AStoker** [comment] 2017-02-15 19:40
Can you look at your network traffic? Is there anything strange happening?
Also, can you reproduce this with a brand new skeleton project?

**Comment by JeroenVinke** [comment] 2017-03-12 22:03
I have tried this in opera and it worked fine for me, so i'm going to close this one for now. Feel free to reopen with steps to reproduce if this is still an issue and we'll take a look at it.

**Closed by JeroenVinke** 2017-03-12 22:03 UTC
Labels: question

**Comment by mosconi** [comment] 2017-07-29 21:01
I have tried the ESNext skeleton  in opera, and still downloading a binary file.

**Comment by JeroenVinke** [comment] 2017-07-29 21:28
This is really strange, I'm not sure why it would do that. Like I said, I can't reproduce it yet so if you can debug it please do!
