### ISSUE TITLE
Dependencies are bundled in the wrong order

### ISSUE THREAD

**Issue by jsobell** [aurelia/cli#257] opened 2016-08-03 02:25 UTC
If you create a new default typescript project, add bootstrap and jQuery, then apply the dependency to the bundle as documented it works:

```
"dependencies": [
  "jquery",
  {
    "name": "bootstrap",
    "path": "../node_modules/bootstrap/dist",
    "main": "js/bootstrap.min",
    "deps": ["jquery"],
    "exports": "$"
  }
]
```

Now, remove jasmine from the project (don't ask, I had to experiment to find the error in my project) and the vendor bundle contains bootstrap _before_ jQuery, so the application fails on startup.

**Comment by zamotany** [comment] 2016-08-03 09:35
Funny thing is that I had to add bootstrap before jquery, otherwise bootstrap' js will give error that jquery is reauired. When I looked into vendor bundle jquery was after bootstrap for some reason.

**Comment by nenadvicentic** [comment] 2016-08-05 17:29
I had exactly the same problem. `au build` would work every 3rd-4th time.
After I kept "jquery" as first dependency and moved "bootstrap" at the end of list, issue was gone.

**Comment by soarer25** [comment] 2016-08-10 08:19
Hi - same issue here,
I'm trying to add materialzecss to the basic template created by 'au new'.  I'm intermittently getting a 'Mismatched anonymous define' error. If I touch a source file (say add a space character and rebuild and re-run it'll work. Stop the app - re-run again (au run) and I get the mismatch error again.
Very odd - not sure whats causing it right now but a bit wary of the aurelia cli right now

**Comment by alexisargyris** [comment] 2016-08-14 23:54
Hi,

I confirm that right now Bootstrap is bundled _before_ jquery, so the documented jquery/bootstrap bundling does not work - at least if _no_ testing was selected while creating the project with the CLI. The only workaround is to move the bootstrap-specific declaration to the bottom of the bundling dependency list as @nenadvicentic said.

**Comment by icegnome** [comment] 2016-08-16 23:28
+1   
For me, seemingly randomly jquery and bootstrap will bundle out of expected order.  Editing the aurelia.json file and rebuilding fixes, but remains annoying.

**Comment by geleto** [comment] 2016-08-26 14:20
A workaround for this is to use prepend
For instance instead of adding jquery to the dependencies, use
`"prepend": "node_modules/jquery/dist/jquery.js"]`

**Comment by EisenbergEffect** [comment] 2016-10-07 01:48
Is this still happening in the latest release?

**Comment by zezelazo** [comment] 2016-10-13 22:10
Still happening, now with jquery-ui here is how i solved thanks to the @geleto comment nice trick put it on prepend.

`"name": "vendor-bundle.js",
        "prepend": [
          "node_modules/jquery/dist/jquery.js",
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "scripts/require.js"
        ],
        "dependencies": [
          "aurelia-binding",
          "aurelia-bootstrapper",
          "aurelia-dependency-injection",
          "aurelia-event-aggregator",
          "aurelia-framework",
          "aurelia-history",
          "aurelia-history-browser",
          "aurelia-loader",
          "aurelia-loader-default",
          "aurelia-logging",
          "aurelia-logging-console",
          "aurelia-metadata",
          "aurelia-pal",
          "aurelia-pal-browser",
          "aurelia-path",
          "aurelia-polyfills",
          "aurelia-route-recognizer",
          "aurelia-router",
          "aurelia-task-queue",
          "aurelia-templating",
          "aurelia-templating-binding", 
          "jquery",
          {
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist",
            "main": "js/bootstrap.min",
            "deps": ["jquery"],
            "exports": "$",
            "resources": [
              "css/bootstrap.css"
            ]
          },
          {
            "name": "datatables.net",
            "path": "../node_modules/datatables.net/js",
            "main": "jquery.dataTables",
            "deps": ["jquery"],
            "exports": "$"
          },
          {
            "name": "bootstrap-datetimepicker",
            "path": "../node_modules/bootstrap-datetimepicker/src",
            "main": "js/bootstrap-datetimepicker",
            "deps": ["jquery"],
            "exports": "$"
          },
          {
            "name": "moment",
            "path": "../node_modules/moment/min",
            "main": "moment.min"
          },
          {
            "name": "nprogress",
            "path": "../node_modules/nprogress",
            "main": "nprogress",
            "resources": [
              "nprogress.css"
            ]
          },
          {
            "name": "sweetalert",
            "path": "../node_modules/sweetalert/dist",
            "main": "sweetalert.min",
            "deps": ["jquery"],
            "resources": [
              "sweetalert.css"
            ]
          },
          {
            "name":"jquery-ui",
            "path":"../libs/jquery-ui",
            "main":"jquery-ui.min",
            "deps": ["jquery"],
            "exports": "$"
          },`

**Comment by AStoker** [comment] 2016-10-14 13:24
@zezelazo, that's what we did until we needed to list `jQuery` as a dependency (and therefore as a named install too). This resulted in two versions of jQuery being loaded up which caused other rippling problems. It seems that there is still some strangeness in ordering the deps, but it seems a bit inconsistent and dependent on what dependency tree you create.

**Comment by corneliutusnea** [comment] 2016-12-07 06:02
This is related to my issue (if not a duplicate of) #401

**Comment by AStoker** [comment] 2016-12-07 13:56
@corneliutusnea, maybe :) I'm still waiting to see the `aurelia.json` file to see if it is.  
There does appear to be an [issue](https://github.com/aurelia/cli/issues/378) with generating consistent vendor bundles

**Comment by corneliutusnea** [comment] 2016-12-07 22:05
@AStoker  here is my aurelia.json https://gist.github.com/corneliutusnea/fa0e147df9a9ddb024ee8b65f1851ee8

**Comment by alpox** [comment] 2016-12-07 23:43
I may have some input to this one.

I wrote a fix for a deeper source location possibility (src file not in root folder): https://github.com/aurelia/cli/pull/427
During the progress i found some strange things happening to the dependency load order too - since i do some asynchronous folder lookups, the dependency order came wrong in most cases.

I tracked this issue down and found the bad-boy. (Fixed it also in the pull request)
The issue seems to have its root in the `aurelia-cli/lib/build/bundle.js` file in the code:
```
static create(bundler, config) {
    let bundle = new exports.Bundle(bundler, config);
    let dependencies = config.dependencies || [];

    return Promise.all(
      dependencies
        .filter(x => bundler.itemIncludedInBuild(x))
        .map(dependency => bundler.configureDependency(dependency)
        .then(description => bundle.addDependency(description)))
    ).then(() => bundle);
  }
```

`bundler.configureDependency` is an asynchronous task. since all `configureDependency` get called at one point and are waiting for finish, the promises are able to resolve in different order than they occur in the `dependencies` array and are therefore also added to the bundle in a different order.

I fixed this with the following:
```
 static create(bundler, config) {
    let bundle = new exports.Bundle(bundler, config);
    let dependencies = config.dependencies || [];

    return Promise.all(
      dependencies
        .filter(x => bundler.itemIncludedInBuild(x))
        .map(dependency => bundler.configureDependency(dependency))
    )
    // Add dependencies in the same order as they were entered
    // to prevent a wrong module load order.
    .then(descriptions => 
      descriptions.forEach(description => 
        bundle.addDependency(description)))
    .then(() => bundle);
  }
```

This code waits for all promises to be done and then adds the descriptions in the order as they have been in the `dependencies` array.

I hope this clears things up a bit.

**Comment by jonthenerd** [comment] 2016-12-29 16:14
FYI this occurs when following the Contact Manager tutorial listed in Aurelia documentation and using typescript. Fairly quick to reproduce just following the tutorial.

**Comment by alpox** [comment] 2016-12-29 16:18
This should be fixed with the inclusion of https://github.com/aurelia/cli/pull/427

**Closed** 2016-12-29 16:34 UTC
Labels: bug

**Comment by MaximBalaganskiy** [comment] 2018-04-08 12:49
This is now happening with CLI 0.33.1, jquery, and materialize-amd (and AMD build of materialize-css). Even though jquery is listed before materialize... Prepend solves it.

**Comment by JeroenVinke** [comment] 2018-07-18 18:38
@eastermike can you share a small reproduction of the problem?

**Comment by Alexander-Taran** [comment] 2018-08-16 17:00
I remember there was an issue with a PR for deterministic bundles. That ordered dependencies by path/filename.. to have consistent hash so bundles would not be changed/redeployed/redownloaded between builds if nothing changed in the bundle.

**Comment by huochunpeng** [comment] 2018-08-16 23:52
@eastermike is right, currently deps are sorted by path to maintain consistent output. I encountered same issue when developing auto-trace #862, which I then updated the sorting algorithm to add shim deps in consideration too. auto-trace fixed this.

The fact is, the existing possible wrong order of deps only affects module shipped in a format that executes immediately. Something like this (copied from materialize-amd):
```js
(function($) {
  // ...
}(jQuery)); // immediately require jquery
```
This above code are executed when browser reads bundle files. The other fact is, jquery module itself (which support UMD) is executed immediately too (it got no problem because jquery doesn't depend on anything), if jquery is packed before materialize-amd, you are fine. But since "jquery" is alphabetically behind "materialize-amd", you are toasted with current cli.

@MaximBalaganskiy I am sorry, even with auto-trace cli, materialize-amd doesn't work, it does many inline defines, and does a big `require(['global', 'initial', 'animation',...` to use those inline defined modules. Auto-trace got very confused. I am afraid you have to load jquery and materialize-css (not the amd wrapper) module directly in prepend, just as what you are doing now.

If a module got proper UMD wrapper, like current bootstrap v4, the module code is executed at module loading time (`import "bootstrap";`) which will ensure load its deps before it. The kind of modules are immune to the order of modules in bundle files, this is what an AMD module supposes to behave.

A proper UMD wrapper looks like this, the factory func execution is delayed to the time when the module is required:
```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('jquery'), require('popper.js')) :
  typeof define === 'function' && define.amd ? define(['exports', 'jquery', 'popper.js'], factory) :
  (factory((global.bootstrap = {}),global.jQuery,global.Popper));
}(this, (function (exports,$,Popper) {
  //...
})));
```

One possible fix to the above ordering issue is to use wrapShim which tries to enforce execution at module requiring time. But this trick is not guaranteed to work on all sort of wild legacy npm packages. To try wrapShim, edit aurelia.json

```
"loader": {
  "type": "require",
  "config": { "wrapShim": true },
  //...
}
```

**Comment by MaximBalaganskiy** [comment] 2018-08-16 23:57
Luckily for me, it's not relevant anymore as materialize V1 is a proper AMD module and doesn't have jQuery dependency as well

**Comment by huochunpeng** [comment] 2018-08-16 23:59
Great to hear :-)

**Comment by huochunpeng** [comment] 2018-08-17 00:43
@MaximBalaganskiy a small trouble with `materialize-css` `1.0.0-rc.2`. I don't know why they define the module under name "M", not "materialize-css".
```js
define('M', [], function () {
    return M;
});
```

I have to an alias in auto-trace cli to get it work
```
{
  "name": "M",
  "path": "../node_modules/materialize-css/dist/js/materialize.js"
}
```
Also has to match the name with `import 'M';` and `<require from="M/css/materialize.css"></require>`.

In fact, `materialize-css` doesn't have to define a named module, using anonymous module can work with requirejs in general, with/without cli.

This should be better for them.
```js
define([], function () {
    return M;
});
```

If you look at my above snippet from bootstrap v4, it uses anonymous module too. I would suggest you make a PR to `materialize-css` before they release v1.

With anonymous module, everything is auto traced. Then you just use `import 'materialize-css';` and `<require from="materialize-css/css/materialize.css"></require>`.

**Comment by MaximBalaganskiy** [comment] 2018-08-17 00:55
Not sure what auto-trace does but I've written these docs https://aurelia-ui-toolkits-1.gitbook.io/materialize-bridge-docs/2.-installation/aurelia-cli which work fine...

**Comment by huochunpeng** [comment] 2018-08-17 03:34
Update: auto-trace is updated to improve compatibility with named amd module. Just do `import 'materialize-css';` for the js part.
