### ISSUE TITLE
au-build fails silently when including globalize.js in the bundle

### ISSUE THREAD

**Issue by samppis** [aurelia/cli#672] opened 2017-07-03 08:07 UTC
**I'm submitting a bug report**

* **Library Version:**
0.30.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
7.0.0

* **NPM Version:**
4.0.1

* **Browser:**
Chrome 59

* **Language:**
TypeScript 2.0.6

**Current behavior:**
Including globalize.js in vendor-bundle.js causes `au build` to silently quit (without any errors or warnings) after `tracing globalize` line has been printed on the console. Globalize.js is included in the bundle like this:

```javascript
{
   "name": "globalize",
   "main": "./dist/globalize.js",
   "path": "../node_modules/globalize"
}
```

I have also included the cldr modules in the bundle (required by globalize.js) before the above code block. They seem to bundled just fine.

**Expected/desired behavior:**

Run `au build` or `au run` from the command line to reproduce. I would expect globalize.js to be bundled like any other JS library or at least get some error message if the bundling fails.

* **What is the motivation / use case for changing the behavior?**
Would like to be able to use globalize.js with aurelia-cli. So far haven't found any way to get around this issue and any help is much appreciated!

**Comment by JeroenVinke** [comment] 2017-07-03 09:41
I have to investigate why it silently stops building, but this setup worked for me in the end: https://github.com/JeroenVinke/aurelia-cli-globalize. If it doesn't work, you might want to use a plain script tag to load Globalize instead of bundling it up. Let me know how it goes

**Comment by samppis** [comment] 2017-07-03 10:31
Thanks! I got it working by following your example setup although I had to use `import * as Globalize from 'globalize'` instead of `import Globalize from 'globalize'`.

**Comment by JeroenVinke** [comment] 2017-07-03 10:37
Nice!

**Comment by JeroenVinke** [comment] 2017-08-21 08:11
I can't seem to reproduce this in the latest version of the CLI. Since globalize is working now, I'll close this issue.

**Closed by JeroenVinke** 2017-08-21 08:11 UTC
Labels: bug, bundler
