### ISSUE TITLE
Issues in app-bundle.js.map

### ISSUE THREAD

**Issue by geleto** [aurelia/cli#359] opened 2016-10-06 16:24 UTC
**I'm submitting a bug report**

* **Library Version:**
0.20.1

* **Operating System:**
Windows 10

* **Browser:**
Chrome 53.0.2785.143 m

* **Language:**
TypeScript

There are several errors in `app-bundle.js.map`:

- The line` "sourceRoot":"..\\src"` should be `"sourceRoot":"../src"`, or Chrome will not find the files
- The map references files from one library that is part of vendor-bundle, in my case for the class-transformer library with this declaration in aurelia.json:
```
{
  "name":"class-transformer",
  "path":"../node_modules/class-transformer/",
  "main":"index",
  "deps": "aurelia-polyfills"
}
```
... I have no other references to libraries from vendor-bundle
- All html files and the files from the above library are referenced with absolute paths, but Chrome treats them as relative, e.g.: http://localhost:9000/src/C:/Projects/myproject/src/app.html

Edit:  The second issue might be related to #342

**Comment by AStoker** [comment] 2016-10-06 19:42
The `sourceRoot` issue is most likely due to this issue: https://github.com/aurelia/cli/issues/332
Your second issue might be related to this: https://github.com/aurelia/cli/issues/342, where for some reason certain files are getting bundled in the wrong bundle. 
Not sure about the last one. Is that an issue? Or just something that was unexpected?

**Comment by geleto** [comment] 2016-10-06 19:44
Yes, it's an issue - absolute paths in a map file do not work in Chrome

**Comment by AStoker** [comment] 2016-10-06 19:52
What in particular isn't working? I just tested this out on Chrome and it appears to be behaving normally.

**Comment by geleto** [comment] 2016-10-06 19:58
With the `sourceRoot` issue - I get this error:
`Source map http://localhost:9000/scripts/app-bundle.js.map points to the files missing from the workspace: [http://localhost:9000/scripts/..\src/ui/dialogs/dialog.ts, http://localhost:9000/scripts/..\src/app.ts, http://localhost:9000/scripts/..\src/environment.ts, …]`

If I fix it manually, then I get this error:
Source map http://localhost:9000/scripts/app-bundle.js.map points to the files missing from the workspace: [http://localhost:9000/src/C:/Projects/we4/src/app.html, http://localhost:9000/src/C:/Projects/we4/src/ui/property-panels.html, http://localhost:9000/src/C:/Projects/we4/src/ui/sidebar-content.html, …]

If I manually replace the absolute paths with relative - all is ok.

**Comment by AStoker** [comment] 2016-10-06 20:04
IF the issue with the `sourceRoot` is what you mentioned initially with the backslashes vs forward slashes, then the issue I referenced is the problem and should be tracked there. I'm not sure what you did to "fix it manually".  
In regards to the source maps not working, what in particular isn't working, as it works as expected for me.

**Comment by geleto** [comment] 2016-10-06 20:08
The sourceRoot issue is not related to #332 because it is about path separators in aurelia.json and fixing all windows-style path separators in aurelia.json does not resolve the issue.

In regards to the source maps not working, Chrome does not find the files. It searches for `http://localhost:9000/src/C:/Projects/we4/src/app.html` , which obviously can not be found.

**Comment by AStoker** [comment] 2016-10-06 20:24
#332 although only mentions in the title the aurelia.json file, it covers never using those windows separators anywhere else too.  
HTML files are a little strange in source maps, and that might be the problem. I don't get any errors on html files not being found, but you can't view the html files from sourcemaps anyway. Can you reproduce this error on a clean CLI project? I'm curious as to why you would be getting a 404 while I'm not.

**Comment by geleto** [comment] 2016-10-06 20:48
Ok, I created a brand new project. The windows path separator is still there, and the absolute `app.html` path and yet - everything works fine.

**Comment by AStoker** [comment] 2016-10-06 20:53
Yah, the window path separator is still a problem and hasn't been resolved yet.  
I wonder if something in your original setup get hosed. Can you delete your compiled output (including the map files) and give it another go? You haven't modified any of the npm modules in your original project, have you?

**Comment by geleto** [comment] 2016-10-06 21:34
... my post above is wrong, I added the folder to the workspace, but forgot to "establish the mapping" and was too quick to post without checking.

So I can reproduce one of the problems with a brand new project.

I get this error:
Source map http://localhost:9000/scripts/app-bundle.js.map points to the files missing from the workspace: [http://localhost:9000/scripts/..\src/C:/Dropbox/Projects/test/src/app.html]

I open the map file and change the path from
"C:/Dropbox/Projects/test/src/app.html"
to
"app.html"

I add a breakpoint in app.ts and it works. But now - the windows path separator is not a problem, I can see it in the map file, but Chrome does not complain.

**Comment by EisenbergEffect** [comment] 2016-10-07 01:30
Closing this as duplicate since we have the various issues tracked elsewhere.

**Closed by EisenbergEffect** 2016-10-07 01:30 UTC

**Comment by geleto** [comment] 2016-10-07 07:21
The absolute paths for html files is not tracked elsewhere. While I don't need to view the html files from sourcemaps, in Chrome the source map error message contains only the first 3 files and this prevents me from seeing if there are other problems.

**Comment by AStoker** [comment] 2016-10-07 13:01
Sourcemaps for html files don't really work @geleto, don't try and use that as a test for source maps. Html files aren't compiled like Javascript files, and so there isn't anything to actually see. The way that html files get bundled into the application is probably why you're even seeing them in the source map at all, but that should not be a deal breaker for anything, I'm thinking.

**Comment by geleto** [comment] 2016-10-07 13:07
I know that. It still this prevents me from seeing other map file problems because chrome will show only the first 3 missing files - and all of them are .html. Yes, not a deal breaker, still a nuisance if you have to debug such problems.

**Comment by AStoker** [comment] 2016-10-07 13:27
If you can identify where the problem is, could you make a PR with a fix? That would be extremely helpful.

**Comment by AStoker** [comment] 2016-10-10 15:26
So a clean project works fine (forgetting about the path separator since that issue is tracked elsewhere)?

**Comment by geleto** [comment] 2016-10-11 18:06
Yes

**Comment by geleto** [comment] 2016-10-18 08:37
Here's a workaround for the html and the sourceRoot issues, add this function at the end of gulp.series in build.ts:
```typescript
function patchMap(done) {
  console.log("begin patching map file");
  gulp.src(['scripts/app-bundle.js.map'])
    .pipe(mapstream(function (file, cb) {
            var contents = file.contents.toString('utf8');
            contents = contents.replace('..\\\\src', '../src');
            contents = contents.replace( new RegExp(process.cwd().replace(/\\/g, "/")+"/src", 'g'), '.' );
            file.contents = new Buffer(contents, 'utf8');
            cb(null, file);
        }))
    .pipe(gulp.dest('scripts'))
    .on('finish', function () {
      done();
    });
}
```
You'll have to import [map-stream](https://www.npmjs.com/package/map-stream).

BTW, maybe you should rename #332 if it should track all windows-separator related build bugs.
