### ISSUE TITLE
Error: Path variable [contenthash] not implemented in this context: [contenthash].css

### ISSUE THREAD

**Issue by constructor** [aurelia/cli#868] opened 2018-04-10 10:57 UTC
**I'm submitting a bug report**

* **Library Version:**
0.33.1

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.10.0

* **NPM Version:**
5.8.0

* **Browser:**
all 

* **Language:**
TypeScript X.X

* **Loader/bundler:**
Webpack

**Current behavior:**
1) Using Windows 10, I create a new folder and open Powershell.

2) `au new --here` with options:
	3: Webpack
	2: ASP.NET Core
	2: Typescript
	1: Default - No markeup processing
	1: Default - Use standard css
	1: None - Skip testing
	2: No - Skip testing
	1: Visual Studio Code
	1: Yes (Default) - Creates the project structure…
	1: Yes (Default) - Installs all server, client and tooling dependencies…

3) Create app.css with content:
`body { background-color: red; }`
4) Include css in app.ts:
`import './app.css';`
5) `au build --env prod` gives:
Error: Path variable [contenthash] not implemented in this context: [contenthash].css

It seems to be related to:
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/763

I have followed one suggestion from the above link and added mini-css-extract-plugin for latest webpack. This and a few other small changes make my experience with aurelia-cli now much better. Find 
 my changes here: https://github.com/constructor/aurelia-cli-fixes

* **What is the expected behavior?**
To build without errors using latest libs. As a new user this was causing lots of unnecessary pain. It should just work.

* **What is the motivation / use case for changing the behavior?**
So it just works.

**Comment by Alexander-Taran** [comment] 2018-04-10 12:48
Would you like to provide a pull request for it @constructor ?

**Comment by constructor** [comment] 2018-04-10 22:27
@Alexander-Taran yes, I can do that. I have just one question. The changes I made consist of 3 commits that address 3 issues. The main one being the '[contenthash] not implemented' error. This issue was a single commit (af08725fca36d2ab94f408bf9870a8f2e264915e). The other 2 smaller issues were a 404 css error and the addition of a launchSetting for convenient switching of ASPNETCORE_ENVIRONMENT to 'Production' in Visual Studio. One file from the launchSetting change was committed with 404 fixes. Should I resolve this or would they all be taken together?

**Comment by Alexander-Taran** [comment] 2018-04-10 23:24
let's ask @JeroenVinke  (-:

but there is a chance that plugins will get fixed and this won't be needed right?

**Comment by constructor** [comment] 2018-04-11 08:50
@Alexander-Taran Yes, but is that the default position? My experience was I installed the tools and it did not work as expected. At that point many would look elsewhere. It does not matter to me if these changes are included, but it should matter to everyone that the tools work out of the box without issue to give newcomers a pain free experience and let them see just how great Aurelia is.
In [lib/dependencies.json](https://github.com/aurelia/cli/blob/master/lib/dependencies.json) webpack is referenced as `"webpack": "^4.1.1"`. This seems to use the latest build. If the owner of the referenced project then makes breaking changes it breaks the cli. This seems to be the case here. Would it not make sense to reference dependencies that are guaranteed to work at a point in time by referencing a specific version like `"webpack": "4.1.1"`. Is there a reason for this that I am unaware?
There are other questions regarding the contenthash naming of files and asp-append-version="true" together but I will not put these here. Is there a (or what is) the preferred channel for questions, discussion and proposing ideas?

**Comment by Alexander-Taran** [comment] 2018-04-11 18:12
@constructor I totally agree with you on things not working out of the box. That's exactly my position. Apparently webpack devs did not see some of the changes as breaking. 

For a better quicker problem solving, I'd ask you to create separate pull requests for each independent change.
I'm not totally "in" the fixes you are talking about.
If it is not too much to ask could you create 3 separate branches from master and add webpack fixes to one.. and asp.css to another..  so team could merge on case by case basis.

You will probably have to "recreate" your changes in those branches..
Feel free to ping me on gitter/here if you will need any assistance in the process. 

And thank you for your desire to ease new devs in.
If you care that much, I'd love to invite you to aurelia-contrib organisation. (-:

**Comment by constructor** [comment] 2018-04-12 19:45
@Alexander-Taran After reading around about the wider issues caused by the webpack breaking changes, although my changes work (and I am currently using them) it does not seem to be the correct direction to take. The initial problem, that of newly installed aurelia-cli not working, can be fixed by changing  how webpack is referenced in lib/dependencies.json webpack from `"webpack": "^4.1.1"` to `"webpack": "4.1.1"`. This solves the major issues in one go (both 'au run' and build issues). A hotfix for this would take no time? It is after all a single character change. The other minor issues of css 404 out of the box and project cleaning will still remain, but they are not 'breaking' anything and are more minor annoyances for people who like a clean console :) I can update repo tomorrow maybe.

**Comment by Alexander-Taran** [comment] 2018-04-12 23:11
@JeroenVinke what do you think of locking webpack dependency temporarily @ 4.1.1 ?

**Comment by tomstylesncc** [comment] 2018-04-12 23:12
I've not dig into the causes but I can verify that dropping the `^` from the webpack version fixes the build.
Incidentally it was only the prod build that was breaking in our project, both the dev and stage builds were fine. Hope this helps to track down or fix the issue. Thanks for all the work the CLI team have done.

**Comment by Alexander-Taran** [comment] 2018-04-13 08:47
@tomstylesncc it is external to aurelia issue with webpack.. not much the team can do really. apart from locking down the dependency version

**Comment by constructor** [comment] 2018-04-13 12:27
@Alexander-Taran @tomstylesncc There must be a lack of understanding on my part as I can not understand why not reference exactly? I understand that a ^version  is a 'compatible with version' but that still leaves the release open to failure by the dependency (as seems to be in this case). To my mind a specific software release version should not be put at subsequent risk of failure by dependencies. Even if the referenced dependency is supposed to be a ^ compatible version, a release is still at the mercy of any of its dependencies. I do not understand this.

**Comment by Alexander-Taran** [comment] 2018-04-13 22:54
@constructor It might be a convenience for future fixes.. (-:
But with issues like this.. yes.. I think that locking is the way..
But that destroys the daily `npm upgrade` routine.. how much fun is that now? (-:

**Comment by avrahamcool** [comment] 2018-06-06 15:51
I can confirm that locking `webpack` to `4.1.1` fixes the `au build --env prod` issue.
would be nice if someone can comment here when a new version of `webpack` fixes the issue.
(it's ugly to lock version and stop updates)

**Comment by Alexander-Taran** [comment] 2018-06-13 21:50
@avrahamcool can you recheck with latest webpack?

**Comment by avrahamcool** [comment] 2018-06-14 12:48
tested with `4.12.0`. issue is still there..

**Comment by thomas-darling** [comment] 2018-06-28 22:06
Do we know whether this will be fixed elsewhere, or what's going on here?
Seems the issue linked above (webpack-contrib/extract-text-webpack-plugin#763) was closed with a comment stating that we should use something else to extract CSS - which I assume means the CLI needs to be changed accordingly?

This really needs to work out of the box, and just locking the Webpack version is not a sustainable solution, as we'll need the newer Webpack releases for other reasons.

**Comment by JeroenVinke** [comment] 2018-06-29 06:50
@thomas-darling I agree. I'll take a look

**Comment by jawa-the-hutt** [comment] 2018-07-14 22:23
I had this issue today and was able to fix it via the [Mini Css Extract Plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) that was referenced in  [webpack-contrib/extract-text-webpack-plugin/#763](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/763)
  

Below are the relevant (and commented out) parts of my webpack.config.js that I used.  Your mileage may vary depending on how you usually customize this stuff for your builds.

`const MiniCssExtractPlugin = require('mini-css-extract-plugin');`

```
{
  test: /\.css$/i,
  issuer: [{ not: [{ test: /\.html$/i }] }],
  use: [
    !extractCss ? ['style-loader', ...cssRules] : MiniCssExtractPlugin.loader, 'css-loader'
  ]          
  // use: extractCss ? ExtractTextPlugin.extract({
  //     fallback: 'style-loader',
  //     use: cssRules
  // }) : ['style-loader', ...cssRules]
},
```

```
  // ...when(extractCss, new ExtractTextPlugin({
  //     filename: production ? '[contenthash].css' : '[id].css',
  //     allChunks: true,
  //   })),
  ...when(extractCss, new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: '[name].css',
      chunkFilename: '[id].css'
  })),
```

**Comment by JeroenVinke** [comment] 2018-07-19 11:00
Thanks everyone! https://github.com/aurelia/cli/commit/e9641e4c86fe0e08ecd18dbe96ace8d69fe05a7b

**Closed by JeroenVinke** 2018-07-19 11:00 UTC

**Comment by gcastre** [comment] 2018-07-25 15:04
@JeroenVinke I'm still having this issue after updating the aurelia cli using the guide here https://aurelia.io/docs/cli/updating/

Am I missing something ?

**Comment by JeroenVinke** [comment] 2018-07-25 15:24
@gcastre we are currently doing last testing before we create the release. Until then you might be able to install from the master branch instead of installing the latest version (something like `npm install github:aurelia/cli.git#master`)
