### ISSUE TITLE
Template bundling injected link doesn't respect baseURL

### ISSUE THREAD

**Issue by SPARTAN563** [aurelia/cli#157] opened 2015-08-20 13:40 UTC
The injected `<link rel="import" ...` used to include a template bundle is always forced to be relative in [src/lib/bundler/template-bundler.js](https://github.com/aurelia/cli/blob/master/src/lib/bundler/template-bundler.js#L67) - this results in an infinite recursion within the client's browser when visiting a page whose path results in a request for the bundle AND your server is configured to serve `index.html` for all unknown routes (common practice for applicatoins making use of the HTML5 History API.

This poses a problem in situations where you are making use of template bundling in combination with the HTML5 History API - and represents a deviation from the behaviour of JSPM under similar situations when `baseURL` is set in *config.js*.

To reproduce the error, use template bundling and the History API router mode while visiting <http://localhost:9000/test/test> - you should find that the site never finishes loading (and possibly hangs your web browser). Similarly, if you visit <http://localhost:9000/test> the site will load correctly and function without issues.

The issue is introduced in [src/lib/bundler/template-bundler.js](https://github.com/aurelia/cli/blob/master/src/lib/bundler/template-bundler.js#L67) as a result of the forced `./` prepending to the path of the bundle when injecting the link. Ideally this should default to `./` if `baseURL` is not specified in *config.js*, prepending the value of `baseURL` instead when it is available.

Please let me know if you need anything further from me to help expedite solving this problem, as it is giving us a bit of a headache at the moment and we are having to work around it using some (hacky) server configurations.

**Comment by EisenbergEffect** [comment] 2015-08-20 14:47
Thanks for catching this! @ahmedshuhel Can you follow up and try to resolve this asap? Since this is a fundamental block for those using push state, can you prioritize this and make a release as soon as it is addressed? Thanks!

**Comment by SPARTAN563** [comment] 2015-08-20 18:47
In the mean time, the fix we're using on NGINX to circumvent this issue is to add the following:

```
// Any URL ending in /dist/app-bundle.html (replace if you're using a different file address)
location ~ /dist/app-bundle\.html {
    try_files /dist/app-bundle.html =404;
}
```

Hope this helps anybody who bumps heads with the issue, you should be able to duplicate the functionality in most web servers using a simple URL rewrite.

**Comment by ahmedshuhel** [comment] 2015-08-22 16:09
@SPARTAN563 Is it the link path that creating the problem?  Could you please share your `aureliafile`, `config.js` and project structure? `inject` just creates a `link` in `index.html` for the `bundle-html`.  Is it miscalculating the path? If the path is wrong you always can fix it in `index.html` manually or turn off the `inject` form template bundling. As you are saying you need a web server path redirect to make it work makes me wonder if the problem is somewhere else. It would be nice if you can point me to a github repo that I can use to debug. In the meantime, I am trying to reproduce the problem with skeleton-navigation.

**Comment by SPARTAN563** [comment] 2015-08-22 22:18
Hi @ahmedshuhel - I'm afraid the project is closed source but if you've got any specific queries about components thereof I'd be happy to explain them.

You are correct, it is simply that the path being injected into the `index.html` file is incorrect. One would expect that by specifying `baseURL: '/'` in `config.js` (which has the effect of resolving all JSPM bundles from the root directory) you would see the same result with HTML bundles - instead the injected bundle URL is forced to start with `./` which will result in the browser resolving from the current path.

This results in the following behaviour, which (as you can see in **3.**) will result in breakages on servers configured to return `index.html` for unknown paths.

1. `http://localhost:9000/` + `./dist/app-bundle.html` = `http://localhost:9000/dist/app-bundle.html`
2. `http://localhost:9000/test` + `./dist/app-bundle.html` = `http://localhost:9000/dist/app-bundle.html`
3. `http://localhost:9000/test/123` + `./dist/app-bundle.html` = `http://localhost:9000/test/dist/app-bundle.html`

If you struggle to get a repro case going, let me know and I'll try to squeeze it in on Monday/Tuesday depending on what my schedule looks like. I'll also be available to answer questions you have throughout the week and provide assistance testing fixes.

As for why I opted to place the fix in the webserver's config: it did not require any changes to the build/test/deployment process we have in place, did not require us to make changes to the structure of our codebase to address a (hopefully) transient issue in the bundler and would transparently fall away when the issue in the bundler was addressed.

The process we make use of involves local developer hosted versions of the codebase which *do not* make use of bundling so as to allow rapid changes through BrowserSync with no build times. When we then make a build (which is done using Gulp on an automated CI server) we run `aurelia bundle` which generates the JS bundles, injects them into `config.js` and the HTML templates which are injected into a special `index.bundled.html` - this is all deployed to the testing/production server (depending on the branch) and served from there. We've opted to keep `index.bundled.html` out of version control since it is effectively a copy of `index.html` with some machine generated additions/changes - the last thing we need is somebody new to the codebase making a change to `index.html` and failing to update `index.bundled.html` and breaking things...

**Comment by EisenbergEffect** [comment] 2015-10-26 14:57
@ahmedshuhel Has this been resolved? Can we close this?

**Comment by ahmedshuhel** [comment] 2015-10-27 11:13
@EisenbergEffect @SPARTAN563  Sorry forgot about this one. This issue is related to current `htmlimports` based bundling. I am migrating the issue [here](https://github.com/aurelia/bundler/issues/27) . I will be needing some help from @SPARTAN563 to reproduce this locally.

**Closed by ahmedshuhel** 2015-10-27 11:13 UTC
