### ISSUE TITLE
aurelia.js has Windows line-endings

### ISSUE THREAD

**Issue by m2w** [aurelia/cli#59] opened 2015-05-20 09:27 UTC
Running `aurelia` after a fresh install via `npm install -g aurelia-cli` results in `env: node\r: No such file or directory` due to being saved with CRLF:

```
cat -ev `which aurelia`

#!/usr/bin/env node^M$
...
```

OSX 10.10.3
`node -v` v0.12.2
`npm -v` 2.7.6
`npm -g list | grep aurelia` aurelia-cli@0.1.2

**Comment by ahmedshuhel** [comment] 2015-05-20 09:30
Sorry about that. this will be fixed in the next release version.

**Comment by m2w** [comment] 2015-05-20 09:45
@ahmedshuhel no worries, thanks for the quick response.

**Comment by ahmedshuhel** [comment] 2015-05-29 09:37
Could we please test to see if this still exists on mac. I have tried on linux and found it working.

**Comment by m2w** [comment] 2015-05-30 00:26
Installing via npm (aurelia-cli@0.2.0) I still get the same issue. But if I clone the repository and look at aurelia.js @ 956de8c it's fine...
To rule out that this is caused by something on my side, it would be good if another OSX user could verify this.

**Comment by ifyio** [comment] 2015-06-09 17:55
I'm also currently getting this issue and i'm on osx

**Comment by ahmedshuhel** [comment] 2015-06-10 06:48
Sorry guys. We will make sure this doesn't happen in the release.

**Comment by mbroadst** [comment] 2015-06-12 12:13
This is still an issue on mac as of last night, running dos2unix on the file works

**Comment by mbroadst** [comment] 2015-06-17 16:41
@ahmedshuhel if you're developing on windows, its probably helpful for you to locally set:

```
git config --global core.autocrlf true
```
to make sure the windows line endings aren't automatically used when comitting

**Comment by zewa666** [comment] 2015-06-17 17:28
Actually Im the microsofty here :) thx for the tip will try it out :+1:

**Comment by ahmedshuhel** [comment] 2015-06-17 21:46
I will filter every file before doing a public release this time and hunt down all the  naughty `line endings`. It will be soul cleaning operation.. :)

**Comment by ahmedshuhel** [comment] 2015-06-17 21:52
@mbroadst The issue is still there because there were no new releases. So you are probably testing the last version(0.2.0). Sorry about the inconvenience, we will try to make sure this gets resolved in the next new release, which will be `0.2.1`.

**Comment by mbroadst** [comment] 2015-06-17 22:02
@ahmedshuhel yeah I haven't actually tested since a week or so ago, and have been using a temporary gulp task for deploys instead. Was just trying to help out in terms of future workflow :) FWIW it might help to add a TravisCI job to catch future issues?

**Comment by ahmedshuhel** [comment] 2015-06-17 22:19
That's a great Idea! We can try that out.

**Comment by mbroadst** [comment] 2015-06-17 22:23
@ahmedshuhel yeah I generally think its a good idea to add TravisCI to all of the aurelia repos, its a free service and you guys already have unit tests written and have npm test targets. It's what it's for :) You should be able to just use something like this as a ```.travis.yml```:

```
language: node_js

# this will opt-in to containerized builds
sudo: false

node_js:
  - "0.10"
  - "0.12"

cache:
  directories:
    - node_modules
```

**Comment by mbroadst** [comment] 2015-06-17 22:24
Or rather I can commit that as a PR for you if you'd like, you'll need to log into Travis and link the project to enable running automated CI tests for this repo

**Comment by ahmedshuhel** [comment] 2015-06-17 22:29
PR's are welcome. We currently don't have may tests but we wish to improve in this area. It will be great if travis can catch the line ending problem.

**Comment by mbroadst** [comment] 2015-06-17 22:36
@ahmedshuhel okay cool, you can see over here that it works fine: https://travis-ci.org/mbroadst/cli. I'll submit the PR with a travis "badge" so you can see last build status in the README.md, but someone on your side will need to log into TravisCI and 'link' the aurelia/cli repo. This would involve someone in the aurelia project logging into Travis, syncing the repos, and flipping a little switch for the "cli" repo

**Comment by mbroadst** [comment] 2015-06-17 22:40
@ahmedshuhel https://github.com/aurelia/cli/pull/108

**Comment by ahmedshuhel** [comment] 2015-06-27 19:45
Any good soul can confirm we still have this problem or not? :smile:

**Comment by ahmedshuhel** [comment] 2015-06-27 19:46
@mbroadst Thanks for the PR.

**Comment by ahmedshuhel** [comment] 2015-07-10 15:16
Closing this. We don't have any report on issue for the last release.

**Closed by ahmedshuhel** 2015-07-10 15:16 UTC
Labels: bug
