### ISSUE TITLE
cli traces wrong type of dependency

### ISSUE THREAD

**Issue by magnusdanielson** [aurelia/cli#1033] opened 2019-02-03 21:48 UTC
I'm submitting a bug report

**Library version** aurelia-cli v1.0.0-beta.10

**Operating System:**Windows 10

**Node Version:** 8.11.3

**NPM Version:**5.6.0

**Browser:** IE 11

**Language: TypeScript** 3.0.3

**Loader/bundler:** RequireJS

**Current behavior:**
The auto tracer imports the UMD version of aurelia-dialog and aurelia-fetch-client which causes error in IE 11. It works in Chrome

**What is the expected behavior?**
The auto tracer should import the AMD version of aurelia-dialog and aurelia-fetch-client

If I add below to aurelia.json dependencies section, it works in IE 11 also.
`
   {  
            "name": "aurelia-dialog",  
            "path": "../node_modules/aurelia-dialog/dist/amd",  
            "main": "aurelia-dialog",  
            "resources": ["resources/*.js"]
          },
          {
            "name": "aurelia-fetch-client",
            "path": "../node_modules/aurelia-fetch-client/dist/amd",
            "main": "aurelia-fetch-client"
          },
`

**Comment by bigopon** [comment] 2019-02-03 21:50
@https://github.com/magnusdanielson thanks for filing this. Its an issue with our recent releases to introduce module field in package json for better bundling/tree shaking. @fkleuver and @EisenbergEffect have fixed this and a set of releases is coming soon. In the mean time, please downgrade to one minor or patch version lower.

Sorry @chunpenghuo

**Comment by huochunpeng** [comment] 2019-02-03 21:50
cli built-in bundler uses package.json `browser` field before `module` and `main` field. The `browser` field in aurelia-dialog points to umd built.

I am interested to know what's the error in IE11.

**Comment by huochunpeng** [comment] 2019-02-03 21:53
@bigopon this is unrelated to the module field.

umd build is from rollup, which replaced dynamic import with static import.

Furthermore, cli built-in bundler does not support dynamic import yet. It will fail on all browser if the module field was used by cli. The browser field in aurelia-dialog overshadowed the troublesome module field.

**Comment by magnusdanielson** [comment] 2019-02-03 22:02
All you guys in the @AureliaEffect team are the greatest! I really love the work you do!

@huochunpeng the error is caused by the class keyword on line 7 ` class Renderer {  ` in umd:aurelia-dialog.js and same problem with line 22 `  class RetryInterceptor {  ` in umd:aurelia-fetch-client.js

I am using "aurelia-dialog": "^2.0.0-rc.3"
and "aurelia-fetch-client": "^1.6.0",

If you have a fix coming you can close this issue. I am happy with my workaround for now.

**Comment by huochunpeng** [comment] 2019-02-03 22:03
This is the root cause, the umd target format is es2015.

https://github.com/aurelia/dialog/blob/fb75f90d87fdfc5bff6d5719355c99e368c2937f/rollup.config.js#L34

**Comment by huochunpeng** [comment] 2019-02-07 19:49
This is fixed by aurelia/dialog#369

**Comment by zewa666** [comment] 2019-02-08 12:23
@huochunpeng I think [i18n](https://github.com/aurelia/i18n/blob/master/package.json#L91) and the [store plugin](https://github.com/aurelia/store/blob/master/package.json#L13) are affected as well by this. Anything we should update there?

**Comment by huochunpeng** [comment] 2019-02-08 12:26
:point_up: @bigopon

**Comment by bigopon** [comment] 2019-02-08 12:32
Newer release of those plugins should not have any issues with CLI anymore, at least I believe so

**Comment by robinchesterman** [comment] 2019-03-21 07:39
Aurelia validation has this issue as well :)

**Comment by huochunpeng** [comment] 2019-04-29 01:06
@bigopon were all Aurelia packages cleaned up?

**Comment by bigopon** [comment] 2019-04-29 01:21
I think so.

**Comment by huochunpeng** [comment] 2019-04-29 01:21
@EisenbergEffect this can be closed.

**Closed** 2019-04-29 06:00 UTC
