### ISSUE TITLE
iOS 9 "TypeError: Attempting to change access mechanism for an unconfigurable property."

### ISSUE THREAD

**Issue by hadrienl** [aurelia/cli#612] opened 2017-04-26 08:45 UTC
**I'm submitting a bug report**

* **Library Version:**
0.26.1

**Please tell us about your environment:**
* **Operating System:**
OSX 10.12

* **Node Version:**
7.4.0

* **NPM Version:**
4.0.5

* **Browser:**
iOS 9 Safari

* **Language:**
ESNext

**Current behavior:**

I have the same issue than [here](https://github.com/aurelia/skeleton-navigation/issues/748) but with aurelia-cli and ESNext on iOS 9. When I load my app on Safari iOS 9, the app load well when in dev env, but in stage env, it doesn't and crash this error : "TypeError: Attempting to change access mechanism for an unconfigurable property."

<img width="1680" alt="capture d ecran 2017-04-26 10 45 05" src="https://cloud.githubusercontent.com/assets/225382/25425814/715e2558-2a6d-11e7-95d8-b8b035e00ae0.png">

**Comment by hadrienl** [comment] 2017-04-26 10:25
The app crash when vendor-bundle.js is uglified (file starting with `function _aureliaConfigureModuleLoader()`). This file is made with `au build`. When I run the app in dev with `au run`, vendor-bundle is not uglified. I've tried copying this file on my remote server, and the error did not appears. There is something in the uglify process which breaks on iOS9.
I can't find where is the difference between the `au build` process and the `au run`.

**Comment by hadrienl** [comment] 2017-04-26 10:56
New indice. If I run `au run --env stage`, then I copy the vendor-bundle.js to my remote server, then it works. The file is uglified, so there is another difference between run and build.

**Comment by SalimDr** [comment] 2017-04-28 12:52
+1, I have exactly the same issue

**Comment by AStoker** [comment] 2017-04-28 20:00
I wonder if it's something related to iOS 9 not compatible with whatever the output of the uglifier is. Do you know if it happens on iOS 10?
@hadrienl, did you look at https://github.com/aurelia/skeleton-navigation/issues/748#issuecomment-297533047 for a solution?

**Comment by hadrienl** [comment] 2017-04-28 20:02
It works with iOS10, it crashed on iOS9 only (and maybe lesser but I haven't tested it). I have tried many things after reading the #748 but nothing worked.

**Comment by AStoker** [comment] 2017-04-28 20:05
It sounds like it's a problem with the uglify options then.
We need two things to move forward  
1. A repository/gist where we can reproduce the issue  
2. Help from the community to dig into specifically what line is causing the issue

**Comment by AmitM30** [comment] 2017-04-29 04:50
Doesn't work on iOS8 too. Have tried

**Comment by JeroenVinke** [comment] 2017-05-03 19:37
@hadrienl @AmitM30 since I don't have easy access to iOS8/iOS9, could you try and find out what code it's failing on?

**Comment by AmitM30** [comment] 2017-05-04 05:02
@JeroenVinke Ok. These are from iOS8.1 (iPhone 6 Simulator)

The error:
![image](https://cloud.githubusercontent.com/assets/10666012/25690918/ad519b5c-30b3-11e7-87ed-528ea48ae217.png)

That bundle (doodle.xxxxxx.bundle.js) has a lot of files (aurelia-framework, application source code, a couple of libraries - self written), so if we need details for those, let me know.

Clicking the **1** in the image above lands me to line 3879 below:
![image](https://cloud.githubusercontent.com/assets/10666012/25690936/d697fb8c-30b3-11e7-9338-75f0353f1430.png)

Clicking the **3** in the image above lands me to line 1378 below:
![image](https://cloud.githubusercontent.com/assets/10666012/25690942/ef1f9bec-30b3-11e7-8a95-2be0d58a4b46.png)

Some troubleshooting, if it helps
![image](https://cloud.githubusercontent.com/assets/10666012/25691054/f2126568-30b4-11e7-9acb-951214e2ea0c.png)

*********** *AppWrapper*
This is class written to read request parameteres from iOS and Android apps and launch the web-application in the web-view.

**Comment by AmitM30** [comment] 2017-05-04 05:24
Build Settings:
```
ENV === 'live' ?
    uglify({ debug: false, mangle: { except: ['cb', '__webpack_require__'] } }) : {}
```

.babelrc
```
"webpack": {
      "plugins": [
        "transform-decorators-legacy",
        "transform-class-properties"
      ],
      "presets": [
        [
          "env",
          {
            "targets": {
              "browsers": [
                "last 2 versions",
                "not ie <= 11"
              ]
            },
            "loose": true,
            "modules": false,
            "include": [
              "transform-es2015-literals",
              "transform-es2015-template-literals"
            ],
            "useBuiltIns": true
          }
        ]
      ]
    }
```

**Comment by JeroenVinke** [comment] 2017-05-04 07:11
@AmitM30 thanks a lot! Make sure that you are on aurelia-pal-browser 1.2.1: https://github.com/aurelia/pal-browser/releases/tag/1.2.1 which should be the fix for this issue

**Comment by hadrienl** [comment] 2017-05-04 07:47
It crashes on the same line for me, I'll get a try : 
<img width="446" alt="capture d ecran 2017-05-04 09 46 56" src="https://cloud.githubusercontent.com/assets/225382/25694383/ab4d4464-30ae-11e7-843f-b4d2ef659712.png">

**Comment by hadrienl** [comment] 2017-05-04 07:50
It works! 🎉 Thank you so much.

**Comment by AmitM30** [comment] 2017-05-04 08:38
Worked for me too ! awesome. Thanks @JeroenVinke

**Comment by JeroenVinke** [comment] 2017-05-04 08:39
Great! Thanks for your help @hadrienl and @AmitM30

**Closed by JeroenVinke** 2017-05-04 08:39 UTC
Labels: bug
