### ISSUE TITLE
Building a Production Bundle from Aurelia-CLI

### ISSUE THREAD

**Issue by fedoranimus** [aurelia/cli#292] opened 2016-08-25 21:39 UTC
**I'm submitting a bug report**
- **Library Version:**
  0.17.0

**Please tell us about your environment:**
- **Operating System:**
  Served on Linux (Ubuntu)
  Built on Windows 10
- **Node Version:**
  6.3.1
- **NPM Version:**
  3.10.6
- **Browser:**
  all
- **Language:**
  TypeScript 2.0

**Current behavior:**
`vendor-bundle.js` is looking in the `node_modules` folder for dependencies after bundling.

The following exception is being thrown: `vendor-bundle.js:4122 GET http://localhost/node_modules/aurelia-templating-resources/dist/amd/aurelia-templating-resources.js`

**Expected/desired behavior:**
run `au build` or `au build --env prod`
Create docker container from Nginx, copy `index.html` and `scripts` folder into public nginx html folder.
- **What is the expected behavior?**
  The `vendor-bundle.js` has all the dependencies required to deploy and run.

**Comment by fedoranimus** [comment] 2016-08-26 01:04
http://stackoverflow.com/questions/39148501/building-a-production-bundle-from-aurelia-cli

I posted a SO question on this topic as well. Not sure if I'm doing something wrong or if it's a bug in the bundler.

**Comment by EisenbergEffect** [comment] 2016-08-26 01:07
I'm baffled by this. I haven't seen this happen ever. Do you have some virtual file system configuration or something?

**Comment by fedoranimus** [comment] 2016-08-26 01:11
Nope. I'm bundling on a Windows machine and then running a trivial Dockerfile via Dockercloud and deploying it to Digital Ocean.

```
FROM nginx

COPY index.html /usr/share/nginx/html
COPY scripts /usr/share/nginx/html/scripts
```

**Comment by EisenbergEffect** [comment] 2016-08-26 01:12
Does it run correctly locally?

**Comment by fedoranimus** [comment] 2016-08-26 01:13
Yes.

**Comment by EisenbergEffect** [comment] 2016-08-26 01:18
That is really, very odd. When you load it locally, can you see if it's making the same request? Or is it able to find it in the bundle?

**Comment by fedoranimus** [comment] 2016-08-26 10:04
When using `au run --watch` locally, it looks like it's going into the node_modules folder and pulling in whatever modules which have been defined in `aurelia.json` in this manner

```
{
    "name": "aurelia-templating-resources",
    "path": "../node_modules/aurelia-templating-resources/dist/amd",
    "main": "aurelia-templating-resources"
},
```

![image](https://cloud.githubusercontent.com/assets/179260/18001855/d6e1a952-6b52-11e6-8f80-8b4416eb40b7.png)


I'm not sure if this is something the bundler mimics, or if they're truly being server from my local node_modules folder generated by npm.

**Comment by wmkleuver** [comment] 2016-08-27 22:53
Actually I was having exactly the same issue that @fedoranimus described.
I removed the folders `node_modules` and `typings` as well as the bundles (`scripts/app-bundle.js` and `scripts/vendor-bundle.js`), followed by a fresh `npm install` ,`typings install` and `au build --env prod`. 

Then when I performed a deployment again (xcopy the bundles to the wwwroot folder of an ASP.NET project followed by a web deploy to Azure), everything worked fine again.

I can't say if my underlying problem was the same as yours or if my "solution" will work for you. I just wanted to share this information in the hopes that it may help narrow down the problem.

@EisenbergEffect for completeness sake, my environment:

- **Library Version**: 0.18.0

- **Operating System:**
Served from a Microsoft Azure Web App
Built on Windows 10

- **Node Version:**
6.3.0

- **NPM Version:**
3.10.5

- **Browser:**
all

- **Language:**
TypeScript 2.0

The error seemed to happen for every dependency that has been manually configured with the "name", "path" and "main" properties.

Also, the previous deployment (about 5 days ago) - succeeded without any of these problems. My environment was identical for as far as I recall.

There have been quite a few occasions where the CLI crashed during a --watch session after saving multiple files at the same time. I have also manually ctrl+c'd out of the CLI a few times. Perhaps the CLI does not like that under certain circumstances.

**Comment by fedoranimus** [comment] 2016-08-27 23:35
I just tried clearing my `node_modules`, `typings`, and bundles with a rebuild and redeploy. Sadly, my configuration is still failing.

I'm seeing the same issue with my "name", "path", "main" depenencies.

**Comment by doktordirk** [comment] 2016-08-28 13:31
related: i had that issue for eg all global resources which didn.t have an import somewhere. after dummy importing them, requirejs could trace them and included them in the bundle

**Comment by fedoranimus** [comment] 2016-08-28 19:18
I suppose an equivalent action would be to remove them from `aurelia.json` if they're not being imported anywhere?

**Comment by wmkleuver** [comment] 2016-08-29 11:54
Now it happened again during `au run --watch` after a production bundle ran without problems yesterday. The only things I did in between is switched to a new git branch and upgraded two npm dependencies.
Similarly, clearing `node_modules` and removing the bundles resolved the issue again.

It is trying to get the files from `node_modules` but cannot seem to find them (even though they are actually there)

Chrome debugger during `au run --watch` **before** clearing the files:
![image](https://cloud.githubusercontent.com/assets/9655331/18050590/d0951120-6def-11e6-9f56-c96b98c4a6b0.png)

Chrome debugger during `au run --watch` **after** clearing the files:
![image](https://cloud.githubusercontent.com/assets/9655331/18050616/fbfe313e-6def-11e6-830e-9b14de863174.png)

**Comment by sergiuoala** [comment] 2016-08-29 12:26
I confirm, I'm experiencing the same issue.

**Comment by fedoranimus** [comment] 2016-08-29 15:39
So, possibly it's for "name", "path, "main" dependencies which are not directly imported? RequireJS is having difficulty tracing them?

**Comment by wmkleuver** [comment] 2016-08-29 16:48
@fedoranimus I do actually import all of my "name", "path", "main" dependencies in one place or another. I have tried removing these imports but everything still worked. For good measure I cleared `node_modules` and removed the bundles and tried again, but it still worked.

Up until now I didn't even realize that it's not necessary to import these..

**Comment by fedoranimus** [comment] 2016-08-29 17:01
@wmkleuver Interesting, okay.

**Comment by wmkleuver** [comment] 2016-08-29 21:08
Some additional info:

It just happened again when running without the `--env` param, right after I did a deployment with `--env prod`. Zero changes in between.

I then did the following experiment:
- Moved the broken app-bundle.js and vendor-bundle.js from `scripts` to a temporary folder
- Re-ran the CLI without `--env` -> it worked again
- Moved the working bundles to another temporary folder
- Moved the broken bundles from the first temporary folder back into `scripts` 
- Re-ran the CLI without `--env` -> the problem came back
- Switched the bundles again -> it worked again

Something is left behind in the bundles somehow. For me it only happens when building with different `--env` params consecutively (in both directions), but not all the time.

A quick comparison on the bundles only showed some differences in the ordering but I believe that's non-deterministic anyway. Sizes are identical to the bit and so are the environment-specific variables.
Yet one works and the other does not..

**Comment by fedoranimus** [comment] 2016-09-09 11:47
After trying all these tricks, I still have been unable to have my bundle be created properly.

**Comment by fedoranimus** [comment] 2016-09-16 13:03
I would just like to reiterate that this is a significant blocking issue for staging and production use; is there any additional information I can provide that would help resolve this issue?

**Comment by EisenbergEffect** [comment] 2016-09-16 13:20
@fedoranimus The best way to see this addressed is to do some digging and make some recommended solutions to us or submit a PR.

**Comment by fedoranimus** [comment] 2016-09-18 14:23
I've done some additional digging. I'm able to see the modules in the bundle (with all environment settings).

However, when `require(...)` is called on the module, it fails to find it in `node_modules`, since `node_modules` doesn't exist.

I do not see a difference in the bundle between modules defined in this pattern which are found and those which are not.

I do not know much about the inner workings of requirejs; I'll continue looking into this today.

**Comment by arabsight** [comment] 2016-09-18 19:00
This problem happened to me with a plugin I was writing that defines a global resource which doesn't get imported or exported anywhere else. I noticed in dev tools that *mdl.js* a file defined as a global resource was requested from *node_modules*:

```html
<head>
    <title>Aurelia</title>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="main" src="src/../scripts/app-bundle.js"></script>
    <script type="text/javascript" charset="utf-8" async="" data-requirecontext="_" data-requiremodule="aurelia-mdl-plugin/mdl" src="src/../node_modules/aurelia-mdl-plugin/dist/amd/mdl.js"></script>
    <style type="text/css">.aurelia-hide { display:none !important; }</style>
</head>
```
aurelia-cli is using a tool called [amodro-trace](https://www.npmjs.com/package/amodro-trace) to trace module's nested dependencies but it doesn't trace ``` globalResources('./mdl') ```.
I logged the traced modules here: [bundled-source.js](https://github.com/aurelia/cli/blob/master/lib/build/bundled-source.js#L103) and this was the result:

```
...
------
Tracing material-design-lite/material...
Tracing mdl-selectfield/mdl-selectfield...
Tracing aurelia-mdl-plugin...
------
	Module ID: aurelia-mdl-plugin/config
	Module ID: aurelia-mdl-plugin/index
------
Tracing font-awesome...
Writing app-bundle.js...
Writing vendor-bundle.js...
Finished 'writeBundles'
```

since not all plugins have this problem I looked at aurelia-validation it have 3 globalResources but they have been [exported](https://github.com/aurelia/validation/blob/master/src/aurelia-validation.ts) which makes them traceable.

so if I export or dummy import the class it gets traced:
```
Tracing aurelia-mdl-plugin...
------
	Module ID: aurelia-mdl-plugin/config
	Module ID: aurelia-pal
	Module ID: aurelia-metadata
	Module ID: aurelia-dependency-injection
	Module ID: aurelia-logging
	Module ID: aurelia-task-queue
	Module ID: aurelia-binding
	Module ID: aurelia-path
	Module ID: aurelia-loader
	Module ID: aurelia-templating
	Module ID: aurelia-framework
	Module ID: aurelia-mdl-plugin/mdl
	Module ID: aurelia-mdl-plugin/index
------
```

@fedoranimus I'm wondering what modules/plugins are causing you trouble?

**Comment by EisenbergEffect** [comment] 2016-09-18 19:19
If you have code that isn't "imported" through the module system, then it can't be traced. You would need to use the blog pattern to include it or else import it somewhere.

**Comment by fedoranimus** [comment] 2016-09-18 19:53
@arabsight `aurelia-templating-resources` is causing me trouble. I can see that it's not being traced when I do a build. [I've created a gist of my `aurelia.json`](https://gist.github.com/fedoranimus/3623e5098b4bae3938579d6bcda9ae4a).
```
...
Tracing aurelia-logging-console... 
Tracing aurelia-templating-binding...
Tracing jquery...
Tracing aurelia-templating-router...
Tracing tether/css/tether...
Tracing tether...
Tracing bootstrap/css/bootstrap...
Tracing bootstrap...
Writing app-bundle.js...
Writing vendor-bundle.js...
Finished 'writeBundles'  
```
I've defined it in my `aurelia.json` in a manner identical to the default.
```
...
{
   "name": "aurelia-templating-resources",
   "path": "../node_modules/aurelia-templating-resources/dist/amd",
   "main": "aurelia-templating-resources"
},
    ...
```

I did a fresh CLI setup and can see that `aurelia-templating-resources` is being traced and is defined in `aurelia.json` in the same manner.

```
Tracing aurelia-templating-binding...
Tracing aurelia-templating-resources...
Tracing aurelia-templating-router...
```

**Comment by doktordirk** [comment] 2016-09-19 05:39
@EisenbergEffect blobs lead to that 'annonymous define' error.

**Comment by fedoranimus** [comment] 2016-09-19 20:08
Just to be explicitly clear, when should a dependency be traced when bundling? What is the expected criteria?

**Comment by fedoranimus** [comment] 2016-09-23 00:00
@doktordirk It looks like `aurelia-authentication` may be involved in some way? It and its dependencies are being pulled in from `node_modules` when debugging. The dependencies align with the issue I'm seeing in production.

![image](https://cloud.githubusercontent.com/assets/179260/18769853/c213fa5e-80fe-11e6-8827-2c253fd190f5.png)

**Comment by doktordirk** [comment] 2016-09-23 08:27
@fedoranimus nah, authentication works fine (if following https://github.com/SpoonX/aurelia-authentication#installation which you seemingly did). but since it is an issue of not waiting for a promise somewhere, it may popup in your setup since you listed it last. you could check by moving it up

**Comment by fedoranimus** [comment] 2016-09-23 10:07
@doktordirk Ah, I see. Thanks.

@EisenbergEffect I updated my `aurelia.json` this morning to follow the pattern outlined #332 , did an `--env prod` build, and it produced a successful production bundle. (I have some other issues with images not being moved, but that's unrelated)

I will continue testing to verify whether or not this is a consistent fix.

**Comment by fedoranimus** [comment] 2016-09-24 11:59
I have been consistently able to produce deployable bundles since updating my `aurelia.json` path separators to be platform agnostic by changing `\\` to `/`.

**Comment by EisenbergEffect** [comment] 2016-09-24 12:03
@fedoranimus Thanks for the update! We recently found a few places where this was causing a problem. We'll get it soon. Thanks for confirming it fixes your scenario!

**Comment by jon123** [comment] 2016-09-29 16:03
Used the above suggestion to change `\\` to `/` (on windows) and that fixed the calls to node_modules when loading aurelia related scripts.  However trying to add any other dependency provokes a call into node_modules.   Things to note is that vendor-bundle.js does have the dependencies in it and everything application wise works as expected. 

I am on version Using version .18 on windows with a default CLI setup and the following two entries shown below are the only ones added:

          "jquery",
          {
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist",
            "main": "js/bootstrap.min",
            "deps": ["jquery"],
            "exports": "$"
          }

The above causes the browser to make a call to node_models/bootstrap/dist/js/boostrap.min.js. 

Adding another lib gives the same result: a call into node_modules to load it 
          {
            "name":"flickity",
            "path":"../node_modules/flickity/dist",
            "main":"flickity.pkgd",
            "resources": [
                  "flickity.css"
                ]
          }

I tried to work around by movingthe .js to the /scripts directory (thereby avoiding node_modules)

        {
            "name":"flickity",
            "path":"../scripts/assets/flickity/dist",
            "main":"flickity.pkgd",
            "resources": [
                  "flickity.css"
                ]
          }

The vendor-bundle works fine and contains the .js from the new location but there is still a call into /scripts to get the .js.  An additional error occurs with this setup: aurelia modules are now calling into node_modules (like when `\\` was used ).   

(As well the .css resource won't load )

**Comment by EisenbergEffect** [comment] 2016-10-03 04:55
@AStoker I know you are poking around in the CLI doing different things now. While you are at it, we need to have a nice way to make sure all file paths that are written have the proper unix format.

**Comment by AStoker** [comment] 2016-10-03 13:03
@EisenbergEffect, rodger that Ghost Rider.
That is currently being tracked here (https://github.com/aurelia/cli/issues/332), right?
This week I'm about to step back into the UI design portion of my job, so I'll be spending more time in front of Illustrator than VS Code 😛 All that to say, if nobody has picked it up by time I get the tdd issue finished, I'll take a peek at that one too.

**Comment by EisenbergEffect** [comment] 2016-10-03 14:39
Sounds good. I just wanted you to be aware of it while you were in there in case you saw an easy way to address it.

**Comment by kahoona77** [comment] 2016-10-06 12:57
Hi I have a similar problem including a client library using aurelia-cli. I npm installed it and then added it to the aurelia.json like this:
```
{
	"name": "toastr",
	"path": "../node_modules/toastr",
	"main": "toastr", 
	"deps": ["jquery"],
	"exports": "$"
},
```
And I import it in my component like this:
```
import * as toastr from 'toastr';
```
When I start with `au run` aurelia / requireJS tries to load it from node_modules `(http://localhost:9000/node_modules/toastr/toastr.js)`. But it should not do that, because the library is already bundled within the vendor-bundle.

When I remove the import, the page gets loaded, but as soon as I try to use the library it is undefined: `ReferenceError: toastr is not defined`

I am also running on windows. I replaced all `\\` with `/` that I found, but the problem still exists.

**Comment by brandonseydel** [comment] 2017-01-20 22:19
I am still facing this issue with aurelia-dragula.  I am trying to trace it down now.

**Comment by JeroenVinke** [comment] 2017-03-16 18:34
I can't seem te reproduce the issue with either toastr or aurelia-dragula when using the latest version of the CLI. And I believe we addressed the path separator problem. So I believe this got fixed. If anyone is still having some issues, let me know

**Closed by JeroenVinke** 2017-03-16 18:34 UTC
Labels: bug
