### ISSUE TITLE
Build emits outputs to wrong directory on ASP.NET Core

### ISSUE THREAD

**Issue by JamesFenton** [aurelia/cli#405] opened 2016-11-09 19:54 UTC
**I'm submitting a bug report**

* **Library Version:**
0.22.0

**Please tell us about your environment:**
* **Operating System:**
Windows 8.1

* **Node Version:**
6.5.0

* **NPM Version:**
3.10.9

* **Browser:**
all

* **Language:**
all

**Current behavior:**
Running `au build` produces the bundles in the ./scripts folder instead of ./wwwroot/scripts in ASP.NET Core projects

**Expected/desired behavior:**

- au new --here
- Choose 2 (ASP.NET Core)
- Choose 1 or 2 (Babel or TypeScript)
- Choose 1 (No CSS pre-processor)
- Choose 1 (Yes for unit testing)
- Choose 1 (Create project)
- Choose 1 (Install dependencies)
- run `au build`
- a 'scripts' folder is created with the bundles in the current folder, not in the wwwroot folder

* **What is the expected behavior?**
The build output should be in ./wwwroot/scripts
This can be fixed after creating the project by changing the `build.targets.output` in aurelia.json from 'scripts' to 'wwwroot/scripts'

* **What is the motivation / use case for changing the behavior?**
index.html cannot load the bundles (404) and the app does not work

**Comment by AStoker** [comment] 2016-11-10 14:00
Reproducible on my machine too.

**Comment by ghidello** [comment] 2016-11-13 08:51
In order to use the **rev** option I also had to update the `build.targets.index` property to `wwwroot/index.html`

**Comment by JamesFenton** [comment] 2016-11-13 10:18
@ghidello I have the same issue. I believe that is related to #357

**Comment by ghidello** [comment] 2016-11-13 22:15
Yes, looks like it's the same thing, thanks for pointing out. I started reading the CLI sources and putting together a solution but now I see it has been closed because they're already working on it. Well, I needed to start somewhere so it was worth it anyway.

**Comment by EisenbergEffect** [comment] 2016-11-19 03:04
Feel free to submit a PR :)

**Comment by malk2013** [comment] 2016-11-26 16:21
hi,
i have started new aurelia project but still this issue is hanging around look at my aurelia.json
"build": {
    "targets": [
      {
        "id": "aspnetcore",
        "displayName": "ASP.NET Core",
        "output": "wwwroot/scripts",
        "index": "wwwroot/index",
        "baseUrl": "scripts"
      }
    ],
when i run ---->    au run     its not showing my default output . please help

**Comment by alvaradojl** [comment] 2016-12-04 08:46
same problem here, the fix is still necessary

**Comment by PWKad** [comment] 2017-01-12 08:27
The fix here for asp.net using --here flag -

1. aurelia.json (all locations)
  a. Change `scripts` to `wwwroot/scripts`
  a. Change `index` to `wwwroot/index.html`
2. run.js
  a. Change baseUrl from `.` to `./wwwroot`

I'll try to PR this and test it but if anyone wants to steal that and PR it it is working for me.

**Comment by aamuz** [comment] 2017-01-18 15:14
any news on this?

**Comment by ghidello** [comment] 2017-01-24 09:11
Hi, I saw that PR #418 has been merged: @aamuz can you test the CLI version from the sources and see if it's working?

**Comment by JeroenVinke** [comment] 2017-03-12 19:12
Yep, I think #418 fixed this (aurelia.json script and index properties contain wwwroot now). The baseURL is still incorrect for new apps though, but that is tracked in https://github.com/aurelia/cli/issues/531

**Closed by JeroenVinke** 2017-03-12 19:12 UTC
Labels: bug
