### ISSUE TITLE
au generate resource - specify path

### ISSUE THREAD

**Issue by marekpw** [aurelia/cli#717] opened 2017-08-23 18:36 UTC
Are there plans to support specifying path for the `au generate` commands? Currently the paths can be specified in aurelia.json but they cannot be changed on per-generation basis. That is not an option for me since my resource tree isn't flat.

Something like `au generate element --path src/components/` would be great.

**Comment by zewa666** [comment] 2017-08-23 20:38
Duplicate of https://github.com/aurelia/cli/issues/466

**Closed by zewa666** 2017-08-23 20:38 UTC
