### ISSUE TITLE
Cannot find module './src/init'

### ISSUE THREAD

**Issue by northamerican** [aurelia/cli#375] opened 2016-10-13 21:44 UTC
* **Library Version:**
0.20.2

* **Operating System:**
OSX 10.12

* **Node Version:**
6.2.0

* **NPM Version:**
3.8.9

* **Language:**
ESNext

**Current behavior:**
`au new` and `au run` are entered as instructed. Instead of building and running, this error is shown:
```
{ Error: Cannot find module './src/init'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/home/Sites/compluter-au/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/index.js:4:9)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3) code: 'MODULE_NOT_FOUND' }
```

**Expected/desired behavior:**
The Aurelia CLI should build and or run when commanded.

**Comment by northamerican** [comment] 2016-10-13 21:45
Reproducible on two Macs both running macOS Sierra. This is with the Aurelia CLI installed on the date of this bug report.

**Comment by dustin486** [comment] 2016-10-13 21:48
@northamerican I was literally about to open an issue on this and saw where you did. I am having the same problem. Running macOS Sierra.

**Comment by northamerican** [comment] 2016-10-13 21:54
directly related: https://github.com/floridoo/gulp-sourcemaps/issues/243

**Comment by MMJM** [comment] 2016-10-13 22:01
Exactly the same happening for me

**Comment by northamerican** [comment] 2016-10-13 22:08
temporary fix: 
`npm install gulp-sourcemaps@2.0.0 --save`
`cd node_modules/vinyl-fs`
`npm install gulp-sourcemaps@2.0.0 --save`

**Comment by dustin486** [comment] 2016-10-13 22:28
`npm install gulp-sourcemaps@2.0.0 --save` worked for me.

**Comment by PWKad** [comment] 2016-10-13 22:40
Can someone try again looks like sourcemap released a fix 10 minutes ago

**Comment by PWKad** [comment] 2016-10-13 22:45
Confirmed it works for me with 2.1.1 `gulp-sourcemaps` if someone else can confirm we can close this and everyone can run `npm install gulp-sourcemaps` if they caught this at the same time.

**Comment by dustin486** [comment] 2016-10-13 22:52
@PWKad I just created a new project and confirm the update `gulp-sourcemaps` pushed fixes the issue. Can be closed.

**Closed** 2016-10-13 23:03 UTC
Labels: bug
